### ISSUE TITLE
Access rights on project boards

### ISSUE THREAD

**Issue by umbert0o** [Gustav-Radbruch-Haus/eva#11]
Which user level (access right) is needed, to create cards on the respective project boards?

**Comment by bitbike** [comment]
Ah. That's a good question. We wanted in the past to do all changes via pull requests. But in the current structure we should rethink  it.

**Comment by umbert0o** [comment]
I likely want to create some cards for basic discussion: tech-stack (DB, spring components..), dockerization, api's, features etc. I guess that would be nice as an overview also we can see the exact status a card/ticket is on.

**Comment by creichel** [comment]
Hello people!
Just spotted the discussion here. I gave you the hopefully necessary rights (Admin or Maintainer, respectively).
Please check if you can access it

**Comment by bitbike** [comment]
Thank you @creichel! Should work for everyone now 👍
